### PR TITLE
Add pipe and promisify

### PR DESCRIPTION
**Pull request by scull7**
- add JW::pipe method
- add JW::promisify method

### CODE REVIEW

**Comment by scull7** [comment]
@mattsmee @jonajonlee @ricejasonf @clydesmyth @mszymulanski @groces Please review

**Comment by mszymulanski** [comment]
@scull7 Can we see an example use in readme file?

**Comment by scull7** [comment]
@mszymulanski that's what the tests are for 😄

**Comment by mszymulanski** [comment]
:shipit:

**Pull request merged**
